{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cla-public.fullname" . -}}
{{- $ingressName := printf "%s-%s" $fullName "v122" -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "cla-public.labels" . | nindent 4 }}
  annotations:
  # Add annotation to exclude 503 error pages from the list the cloud-platform error pages
  # and use our error pages for 503 errors
    nginx.ingress.kubernetes.io/custom-http-errors: "413,502,504"
    {{- if .Values.ingress.cluster.name }}
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $ingressName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{- .Values.ingress.cluster.weight -}}"
    {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-get-access"
      SecRuleRemoveById 942230
      SecRuleRemoveById 930120
      SecRuleRemoveById 933210
spec:
  ingressClassName: "modsec"
  tls:
    - hosts:
       - "{{ .Values.host }}"
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-app
                port:
                  number: {{ $svcPort }}
{{- end }}
