apiVersion: v1
kind: Service
metadata:
  name: {{ include "cla-public.fullname" . }}-app
  labels:
    {{- include "cla-public.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cla-public.selectorLabels" . | nindent 4 }}