---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: laa-cla-public-certificate
  namespace: laa-cla-public-production
spec:
  secretName: laa-cla-public-production-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'checklegalaid.service.gov.uk'
  acme:
    config:
    - domains:
      - 'checklegalaid.service.gov.uk'
      dns01:
        provider: route53-dsd