#!/bin/sh -e
safe_git_branch=${CIRCLE_BRANCH//\//-}
short_sha="$(git rev-parse --short=7 $CIRCLE_SHA1)"
deploy_image_and_tag="$ECR_DOCKER_IMAGE:$safe_git_branch.$short_sha"
ECR_DEPLOY_IMAGE="$ECR_DOCKER_REGISTRY/$deploy_image_and_tag"
