#!/bin/sh -eu

ROOT=$(dirname "$0")
ENVIRONMENT="$1"
ENVIRONMENT_DIR="$ROOT/../kubernetes_deploy/$ENVIRONMENT"

if ! [ -d $ENVIRONMENT_DIR ] ; then
  echo "$ENVIRONMENT_DIR not found"
  exit 1;
fi

source "$ROOT/define_build_environment_variables"

echo "Deploying $ECR_DEPLOY_IMAGE to $ENVIRONMENT..."

kubectl set image --filename="$ENVIRONMENT_DIR/deployment.yml" --local --output=yaml \
  app="$ECR_DEPLOY_IMAGE" | \
  kubectl apply \
    --filename=/dev/stdin \
    --filename="$ENVIRONMENT_DIR/service.yml" \
    --filename="$ENVIRONMENT_DIR/ingress.yml"
