#!/bin/sh -e

source $(dirname "$0")/define_build_environment_variables
environment="$1"

cat <<END > payload.json
{
  "text": ":tada: Deployed \`$deploy_image_and_tag\` to *$environment*.",
  "attachments": [
    {
      "fallback": "<$CIRCLE_BUILD_URL|View build>",
      "actions": [{"type": "button", "text": "View build", "url": "$CIRCLE_BUILD_URL"}]
    }
  ]
}
END

curl --request POST --data @payload.json --header "Content-Type: application/json" $SLACK_WEBHOOK_URL
