# Default values for cla-public in a staging environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent

environment: staging

replicaCount: 2

ingress:
  enabled: true
  secretName: tls-certificate

envVars:
  GDS_GA_ID:
    value: UA-145652997-1
  MOJ_GTM_ID:
    value: GTM-MWL77F6
  MOJ_GTM_AUTH:
    value: "4KOuCU7aXv3Owhcs7U0ORw"
  MOJ_GTM_PREVIEW:
    value: "env-3"
  BACKEND_BASE_URI:
    value: "https://laa-cla-backend-uat.apps.live-1.cloud-platform.service.justice.gov.uk"
  LAALAA_API_HOST:
    value: "https://laa-legal-adviser-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk"
  GOOGLE_MAPS_API_KEY:
    value: "AIzaSyBVsZmfkiRFNNMJnPraN_8sBW3Dj-BFFNs"
  LOG_LEVEL:
    value: "INFO"
  DEBUG:
    value: "False"
