apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laa-cla-public
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: laa-cla-public-app
        env: development
        service_area: laa-get-access
        service_team: cla-fala
    spec:
      containers:
      - image: "<to be set by deploy_to_kubernetes>"
        imagePullPolicy: Never
        name: app
        readinessProbe:
          httpGet:
            path: /ping.json
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping.json
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: http
        env:
        - name: CLA_ENV
          value: development
        - name: BACKEND_BASE_URI
          value: https://staging-backend.cla.dsd.io/
        - name: LAALAA_API_HOST
          value: https://staging.laalaa.dsd.io
        - name: LOG_LEVEL
          value: DEBUG
        - name: SECRET_KEY
          value: "secret"
        - name: OS_PLACES_API_KEY
          value: ""
        - name: ZENDESK_API_TOKEN
          value: ""
        - name: ZENDESK_API_USERNAME
          value: ""
        - name: SMTP_HOST
          value: ""
        - name: SMTP_USER
          value: ""
        - name: SMTP_PASSWORD
          value: ""
        - name: RAVEN_CONFIG_DSN
          value: ""
        - name: RAVEN_CONFIG_SITE
          value: ""
        - name: GOV_NOTIFY_API_KEY
          value: ""
        - name: GOV_NOTIFY_TEMPLATE_CONFIRMATION
          value: ""
