apiVersion: v1
kind: Service
metadata:
  name: laa-cla-public
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30000
  selector:
    app: laa-cla-public-app
