apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy_to_kubernetes script>"
  name: laa-cla-public
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: laa-cla-public-app
        env: staging
        service_area: laa-get-access
        service_team: cla-fala
    spec:
      containers:
      - image: "<to be set by deploy_to_kubernetes>"
        name: app
        readinessProbe:
          httpGet:
            path: /ping.json
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping.json
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: CLA_ENV
          value: staging
        - name: BACKEND_BASE_URI
          value: https://staging-backend.cla.dsd.io/
        - name: LAALAA_API_HOST
          value: https://laa-legal-adviser-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk
        - name: LOG_LEVEL
          value: INFO
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secret-key
              key: SECRET_KEY
        - name: OS_PLACES_API_KEY
          valueFrom:
            secretKeyRef:
              name: os-places
              key: apiKey
        - name: ZENDESK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: zendesk-api
              key: ZENDESK_API_TOKEN
        - name: ZENDESK_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: zendesk-api
              key: ZENDESK_API_USERNAME
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-sendgrid
              key: SMTP_HOST
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-sendgrid
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-sendgrid
              key: SMTP_PASSWORD
        - name: RAVEN_CONFIG_DSN
          valueFrom:
            secretKeyRef:
              name: raven-config
              key: RAVEN_CONFIG_DSN
        - name: RAVEN_CONFIG_SITE
          valueFrom:
            secretKeyRef:
              name: raven-config
              key: RAVEN_CONFIG_SITE
        - name: GOOGLE_MAPS_API_KEY
          value: AIzaSyBVsZmfkiRFNNMJnPraN_8sBW3Dj-BFFNs
